### ISSUE TITLE
Impossible to use /24 subnet

### ISSUE THREAD

**Issue by 7ymekk** [denisix/wireguard#2]
first of all, thanks for your great work.

I tried using this docker image but I found a problem with handling of /24 subnets

using /24 subnet is impossible as addclient builds client's IP like following:

`Address = $SUBNET.$C.$N/$SUBNET_PREFIX`

so when trying to configure it with:

```
      - SUBNET=192.168.255
      - SUBNET_PREFIX=24
      - SUBNET_IP=192.168.255.1/24
 ```

you get client with 192.168.255.0.2/24.

Dockerfile comment says:

` SUBNET=10.88           - Your private subnet without dynamic part`

IMO addclient should build client IP without adding $C, so:

`Address = $SUBNET.$N/$SUBNET_PREFIX`

**Comment by denisix** [comment]
this has been fixed in recent version, now you can use just SUBNET_IP=192.168.255.1 as the base IP address, and the clients will follow this with 192.168.255.1, ...255.2, ...255.3, etc.
